
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'entropy_advisors_test'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'entropy_advisors_test'

# SSL certificate validation is disabled by default. It is legacy behavior which will be changed in future releases.
# It is strongly advised to enable `require_certificate_validation` flag or explicitly set `cert` configuration to `True` for security reasons.
#You may receive an error after that if your SSL setup is incorrect.
flags:
  require_certificate_validation: true

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  entropy_advisors_test:
    # Global post-hooks apply to all models in this project
    +post-hook:
      - sql: "{{ optimize_table(this, model.config.materialized) }}"
        transaction: true
      - sql: "{{ vacuum_table(this, model.config.materialized) }}"
        transaction: true

    # Utility/dimension models shared across layers
    utils:
      +materialized: view
      +view_security: invoker

    # Template reference models (not for production use)
    templates:
      +materialized: view
      +view_security: invoker   # required security setting for views

    # Staging layer: clean raw source data (bronze)
    staging:
      +materialized: view       # default; override to incremental in each model config
      +view_security: invoker

    # Intermediate layer: business logic and cross-protocol joins (silver)
    intermediate:
      +materialized: view       # default; override to incremental in each model config
      +view_security: invoker

    # Marts layer: final analytics-ready tables (gold)
    marts:
      +materialized: table      # default; override in each model config as needed
      +view_security: invoker
